### ISSUE TITLE
Build Favourites Carousel (MVP)

### ISSUE THREAD

**Issue by danwhitlock** [ibalan92/dog-friendly-locations#20]

**Comment by louise-elliott-work** [comment]
For future reference and changes, this is the guide used for creating a star-shaped clickable button:
https://www.freecodecamp.org/news/how-to-make-your-fancy-svg-button-accessible-83c9172c3c15/

**Comment by louise-elliott-work** [comment]
Favorites carousel completed  with Bootstrap placeholder cards and buttons to scroll to next and previous cards.

JQuery CDN also added to HTML as it has been used for the scrolling functionality.
