### ISSUE TITLE
Investigate bootstrap components required

### ISSUE THREAD

**Issue by ibalan92** [ibalan92/dog-friendly-locations#8]

**Comment by louise-elliott-work** [comment]
For our 'favourites' section we can use cards and a carousel.
Here are the Bootstrap docs and a YouTube video about combining them for when we're ready.
https://getbootstrap.com/docs/4.3/components/card/
https://getbootstrap.com/docs/4.3/components/carousel/
https://www.youtube.com/watch?v=kHPm_AlxP7U

Also for the navbar: https://getbootstrap.com/docs/4.0/components/navbar/

And for adding cards to the favourites carousel, we could use an event listener on a button (maybe the star icon):
https://getbootstrap.com/docs/4.0/components/buttons/
https://icons.getbootstrap.com/icons/star/
